version: "3.8"

services:
  redis:
    restart: always
    image: redis:alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"

  springboot:
    restart: always
    container_name: cspeak
    depends_on:
      - redis
      - mongodb
#   이거는 현재 Dockerfile로 빌드를 하는거임
#    build:
#      context: .
#      dockerfile: ./Dockerfile
    # docker hub를 이용하여 이미지를 띄어놓음 그 이미지를 가져오는것
    image: songchoon/cspeak:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  mongodb:
    restart: always
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    container_name: docker-mongodb
    hostname: mongo
